name: notesapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  font_awesome_flutter: ^10.7.0

  cupertino_icons: ^1.0.8
  flutter_quill: ^11.4.1
  provider: ^6.1.2
  intl: ^0.20.2
  firebase_core: ^3.15.1
  firebase_auth: ^5.7.0
  cloud_firestore: 5.6.12
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  flutter_local_notifications: ^17.2.3
  rxdart: ^0.28.0
  timezone: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 

flutter:

  uses-material-design: true

  assets:
    - assets/images/download-removebg-preview.png

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
        - asset: assets/fonts/poppins/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700
    - family: Fredoka
      fonts:
        - asset: assets/fonts/fredoka/Fredoka-Bold.ttf
        - asset: assets/fonts/fredoka/Fredoka-Regular.ttf
          weight: 700
