// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4cvSj0Aj2x4I5tBZsMrPz3pX9lr89dhg',
    appId: '1:936261767673:web:d3d9dd33d8bccc6472ed28',
    messagingSenderId: '936261767673',
    projectId: 'peachpaper-25740',
    authDomain: 'peachpaper-25740.firebaseapp.com',
    storageBucket: 'peachpaper-25740.firebasestorage.app',
    measurementId: 'G-3FP598HEL8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5dA6dP6_aY8vv7H4AU7mzRgn1rPhs9wQ',
    appId: '1:936261767673:android:62f2e87566fcba9c72ed28',
    messagingSenderId: '936261767673',
    projectId: 'peachpaper-25740',
    storageBucket: 'peachpaper-25740.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAttV21oajZRyRK1gFn0P1l3BrfA1kQmAE',
    appId: '1:936261767673:ios:2de984a5d806fd6d72ed28',
    messagingSenderId: '936261767673',
    projectId: 'peachpaper-25740',
    storageBucket: 'peachpaper-25740.firebasestorage.app',
    androidClientId: '936261767673-1f2qphughsthd046ak5haqcf2rcqi732.apps.googleusercontent.com',
    iosClientId: '936261767673-7b1t5908ls8ij2caumrge696d84osbg7.apps.googleusercontent.com',
    iosBundleId: 'com.example.notesapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAttV21oajZRyRK1gFn0P1l3BrfA1kQmAE',
    appId: '1:936261767673:ios:2de984a5d806fd6d72ed28',
    messagingSenderId: '936261767673',
    projectId: 'peachpaper-25740',
    storageBucket: 'peachpaper-25740.firebasestorage.app',
    androidClientId: '936261767673-1f2qphughsthd046ak5haqcf2rcqi732.apps.googleusercontent.com',
    iosClientId: '936261767673-7b1t5908ls8ij2caumrge696d84osbg7.apps.googleusercontent.com',
    iosBundleId: 'com.example.notesapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4cvSj0Aj2x4I5tBZsMrPz3pX9lr89dhg',
    appId: '1:936261767673:web:06694d1417de427772ed28',
    messagingSenderId: '936261767673',
    projectId: 'peachpaper-25740',
    authDomain: 'peachpaper-25740.firebaseapp.com',
    storageBucket: 'peachpaper-25740.firebasestorage.app',
    measurementId: 'G-XNT65QK5M7',
  );

}